name: Build

on:
  push:
    branches:
      - main

jobs:
  build_android:
    name: Build Android App
    type: build
    params:
      platform: android
  build_web:
    name: Build Web App
    type: build
    params:
      platform: web
