name: Build

on:
  push:
    branches:
      - main

jobs:
  build_android:
    name: Build Android App
    type: build
    params:
      platform: android
  deploy:
    type: deploy
    name: Deploy
    environment: production
